"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import Logo from "@/components/brand/Logo";
import SignOutButton from "@/components/dashboard/SignOutButton";

const navigation = [["Dashboard", "/dashboard", "⌂"], ["Goals", "/goals", "◎"], ["Progress", "/progress", "↗"], ["Calendar", "/calendar", "□"]] as const;

export default function AuthenticatedShell({ children, name }: { children: React.ReactNode; name: string }) {
  const pathname = usePathname(); const [menuOpen, setMenuOpen] = useState(false); const initial = name.trim().slice(0, 1).toUpperCase() || "U";
  const nav = (mobile = false) => <nav className={mobile ? "grid grid-cols-5 gap-1" : "space-y-1"} aria-label="Application navigation">{navigation.map(([label, href, icon]) => <Link key={href} href={href} onClick={() => setMenuOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-[13px] font-medium transition ${pathname === href ? "bg-emerald-50 text-emerald-700" : "text-zinc-500 hover:bg-zinc-100 hover:text-zinc-900"} ${mobile ? "flex-col gap-1 px-1 py-2 text-[10px]" : ""}`}><span className="text-[17px] leading-none" aria-hidden>{icon}</span>{label}</Link>)}{!mobile && <><div className="my-4 h-px bg-zinc-200" /><Link href="/settings" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-[13px] font-medium text-zinc-500 transition hover:bg-zinc-100 hover:text-zinc-900"><span className="text-[16px]" aria-hidden>⚙</span>Settings</Link></>}{mobile && <Link href="/settings" onClick={() => setMenuOpen(false)} className={`flex flex-col items-center gap-1 rounded-xl px-1 py-2 text-[10px] font-medium transition ${pathname === "/settings" ? "bg-emerald-50 text-emerald-700" : "text-zinc-500 hover:bg-zinc-100 hover:text-zinc-900"}`}><span className="text-[16px]" aria-hidden>⚙</span>More</Link>}</nav>;
  return <div className="min-h-dvh bg-[#fafaf9] text-zinc-900"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-zinc-200/80 bg-[#fafaf9]/95 px-5 backdrop-blur lg:hidden"><Logo href="/dashboard" /><button type="button" onClick={() => setMenuOpen((open) => !open)} className="flex min-h-11 items-center gap-2 rounded-xl px-2 text-zinc-600 hover:bg-zinc-100" aria-expanded={menuOpen} aria-label="Open account menu"><span className="flex size-8 items-center justify-center rounded-full bg-zinc-900 text-xs font-semibold text-white">{initial}</span><span className="text-sm" aria-hidden>⌄</span></button></header>{menuOpen && <div className="fixed inset-x-0 top-16 z-40 border-b border-zinc-200 bg-[#fafaf9] p-4 shadow-lg lg:hidden"><p className="mb-3 px-3 text-sm font-medium text-zinc-800">{name}</p><SignOutButton /></div>}<div className="flex min-h-dvh"><aside className="hidden w-60 shrink-0 flex-col border-r border-zinc-200/80 bg-[#fafaf9] lg:flex"><div className="flex h-20 items-center px-7"><Logo href="/dashboard" /></div><div className="px-3">{nav()}</div><div className="mt-auto border-t border-zinc-200/80 p-4"><div className="flex items-center gap-3 px-2"><span className="flex size-9 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">{initial}</span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold">{name}</p><SignOutButton /></div></div></div></aside><main className="min-w-0 flex-1 pb-20 lg:pb-0">{children}</main></div><div className="fixed inset-x-0 bottom-0 z-30 border-t border-zinc-200/80 bg-[#fafaf9]/95 px-2 pb-[max(8px,env(safe-area-inset-bottom))] pt-2 backdrop-blur lg:hidden">{nav(true)}</div></div>;
}
