"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import AuthFrame from "@/components/auth/AuthFrame";
import { createClient } from "@/lib/supabase/client";

export default function ForgotPassword() {
  const [pending, setPending] = useState(false); const [sent, setSent] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const email = String(new FormData(event.currentTarget).get("email") ?? "").trim(); if (!email) { setMessage("Enter your email address."); return; } setPending(true); setMessage(""); const { error } = await createClient().auth.resetPasswordForEmail(email, { redirectTo: new URL("/auth/confirm?next=/reset-password", window.location.origin).toString() }); if (error) { setMessage("We couldn’t send a reset link. Please try again."); setPending(false); return; } setSent(true); setPending(false); }
  return <AuthFrame><section className="w-full max-w-md"><div className="mb-8 text-center"><p className="text-sm font-medium text-[#71717A]">Account recovery</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.055em]">Reset your password.</h1><p className="mt-4 text-[15px] leading-7 text-[#52525B]">We’ll send a secure reset link to your inbox.</p></div><div className="rounded-3xl border border-[#E4E4E7] bg-white p-6 shadow-[var(--shadow-md)] sm:p-8">{sent ? <><p role="status" className="rounded-xl bg-[#F0FDF4] px-4 py-3 text-sm leading-6 text-[#166534]">If an account exists for that email, a reset link is on its way.</p><Link href="/login" className="mt-6 inline-flex h-12 w-full items-center justify-center rounded-full bg-[#18181B] text-sm font-semibold text-white">Back to login</Link></> : <form onSubmit={submit} className="space-y-5"><label className="block text-sm font-medium">Email<input name="email" type="email" autoComplete="email" required disabled={pending} className="mt-2 h-12 w-full border border-[#D4D4D8] bg-[#FAFAF9] px-4 outline-none focus:border-[#18181B]" placeholder="you@example.com" /></label>{message && <p role="alert" className="rounded-xl border border-[#FECACA] bg-[#FEF2F2] px-4 py-3 text-sm text-[#B91C1C]">{message}</p>}<button disabled={pending} className="h-12 w-full rounded-full bg-[#18181B] text-sm font-semibold text-white disabled:opacity-60">{pending ? "Sending link…" : "Send reset link"}</button></form>}</div><p className="mt-7 text-center text-sm"><Link href="/login" className="text-[#52525B] underline underline-offset-4">Back to login</Link></p></section></AuthFrame>;
}
