"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import AuthFrame from "@/components/auth/AuthFrame";
import { createClient } from "@/lib/supabase/client";

export default function ResetPassword() {
  const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const form = new FormData(event.currentTarget); const password = String(form.get("password") ?? ""); const confirmation = String(form.get("confirmation") ?? ""); if (password.length < 8) { setMessage("Your password must be at least 8 characters."); return; } if (password !== confirmation) { setMessage("Your passwords don’t match."); return; } setPending(true); setMessage(""); const { error } = await createClient().auth.updateUser({ password }); if (error) { setMessage("This reset link has expired. Request a new one and try again."); setPending(false); return; } setSuccess(true); setPending(false); router.replace("/"); router.refresh(); }
  return <AuthFrame><section className="w-full max-w-md"><div className="mb-8 text-center"><p className="text-sm font-medium text-[#71717A]">Almost there</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.055em]">Set a new password.</h1></div><form onSubmit={submit} className="rounded-3xl border border-[#E4E4E7] bg-white p-6 shadow-[var(--shadow-md)] sm:p-8"><div className="space-y-5"><label className="block text-sm font-medium">New password<input name="password" type="password" autoComplete="new-password" minLength={8} required disabled={pending || success} className="mt-2 h-12 w-full border border-[#D4D4D8] bg-[#FAFAF9] px-4 outline-none focus:border-[#18181B]" /></label><label className="block text-sm font-medium">Confirm new password<input name="confirmation" type="password" autoComplete="new-password" minLength={8} required disabled={pending || success} className="mt-2 h-12 w-full border border-[#D4D4D8] bg-[#FAFAF9] px-4 outline-none focus:border-[#18181B]" /></label>{message && <p role="alert" className="rounded-xl border border-[#FECACA] bg-[#FEF2F2] px-4 py-3 text-sm text-[#B91C1C]">{message}</p>}{success && <p role="status" className="rounded-xl bg-[#F0FDF4] px-4 py-3 text-sm text-[#166534]">Password updated. Taking you back to HabitTracker…</p>}<button disabled={pending || success} className="h-12 w-full rounded-full bg-[#18181B] text-sm font-semibold text-white disabled:opacity-60">{pending ? "Updating password…" : "Update password"}</button></div></form><p className="mt-7 text-center text-sm"><Link href="/login" className="text-[#52525B] underline underline-offset-4">Back to login</Link></p></section></AuthFrame>;
}
